# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Abbey Road' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Abbey Road
  pod 'PureLayout'

end

target 'Abbey Road Host' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Abbey Road Host
  pod 'AudioKit'

end
